[package]
name = "cryptopals-challeges-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
byteorder = "1.5.0"
hex = "0.4.3"
itertools = "0.14.0"
openssl = "0.10.75"
rand = "0.9.2"
